In [2]:
import pandas as pd
train = pd.read_csv('vehicles.csv')
train.head()

              DateTime  Vehicles
0  2015-11-01 00:00:00        15
1  2015-11-01 01:00:00        13
2  2015-11-01 02:00:00        10
3  2015-11-01 03:00:00         7
4  2015-11-01 04:00:00         9

In [3]:
def get_dom(dt):
	return dt.day
def get_weekday(dt):
	return dt.weekday()
def get_hour(dt):
	return dt.hour
def get_year(dt):
	return dt.year
def get_month(dt):
	return dt.month
def get_dayofyear(dt):
	return dt.dayofyear
def get_weekofyear(dt):
	return dt.weekofyear

train['DateTime'] = train['DateTime'].map(pd.to_datetime)
train['date'] = train['DateTime'].map(get_dom)
train['weekday'] = train['DateTime'].map(get_weekday)
train['hour'] = train['DateTime'].map(get_hour)
train['month'] = train['DateTime'].map(get_month)
train['year'] = train['DateTime'].map(get_year)
train['dayofyear'] = train['DateTime'].map(get_dayofyear)
train['weekofyear'] = train['DateTime'].map(get_weekofyear)

train.head()

,DateTime,Vehicles,date,weekday,hour,month,year,dayofyear,weekofyear
0,2015-11-01 00:00:00,15,1,6,0,11,2015,305,44
1,2015-11-01 01:00:00,13,1,6,1,11,2015,305,44
2,2015-11-01 02:00:00,10,1,6,2,11,2015,305,44
3,2015-11-01 03:00:00,7,1,6,3,11,2015,305,44
4,2015-11-01 04:00:00,9,1,6,4,11,2015,305,44

In [4]:
train = train.drop(['DateTime'], axis=1)
train1 = train.drop(['Vehicles'], axis=1)
target = train['Vehicles']
print(train1.head())
target.head()

   date  weekday  hour  month  year  dayofyear  weekofyear
0     1        6     0     11  2015        305          44
1     1        6     1     11  2015        305          44
2     1        6     2     11  2015        305          44
3     1        6     3     11  2015        305          44
4     1        6     4     11  2015        305          44

0    15
1    13
2    10
3     7
4     9
Name: Vehicles, dtype: int64

In [5]:
from sklearn.ensemble import RandomForestRegressor
m1=RandomForestRegressor()
m1.fit(train1,target)
m1.predict([[11,6,0,1,2015,11,2]])

c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([9.35338095])